name: all_emojis
description: This package makes it possible to detect how many browser tabs in the webbrowser your flutter app is currently running in.
version: 0.1.0
homepage: https://famedly.com
repository: https://github.com/famedly/all_emojis

environment:
  sdk: ">=3.4.0 <4.0.0"