name: "All the package specific jobs"

on:
  workflow_call:

jobs:
  pub-dev-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat .github/workflows/versions.env >> $GITHUB_ENV
      - uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46
        with:
          sdk: ${{ env.dart_version }}
      - name: pub.dev publish dry run
        run: |
          dart pub get
          dart pub publish --dry-run